# Configuration file for codecov reporting code coverage

# Disable codecov comments in every PR
comment: off

# Fixes report prefix paths from CI dynamic coverage action
# from https://docs.codecov.io/docs/fixing-paths
fixes:
  - "/__w/ncio/::"

