# Configuration file for codecov reporting code coverage
# at https://codecov.io/gh/ORNL/ncio

# Disable codecov comments in every PR
comment: off

# Ignore testing directory itself
ignore:
  - "testing"

# Fixes report prefix paths from CI dynamic coverage action
# from https://docs.codecov.io/docs/fixing-paths
fixes:
  - "/__w/::"

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: yes
      method: no
      macro: no
