package:
  name: ncio
  version: 1.0.0-alpha.1

source:
  git_url: https://github.com/ORNL/ncio.git
  git_rev: 1.0.0-alpha.1
  git_depth: 1

build:
  number: 0
  string: full  # for full dependencies

requirements:
  build:
  - meson
  - hdf5
  - openmp
  run:
  - hdf5
  - openmp
  
test:
  requires:
    - meson
  commands:
    - meson test
    
about:
  home: https://github.com/ORNL/ncio.git
  license: BSD
  license_file: LICENSE
  summary: No Cost Input Output data management framework

# build:  conda build -c conda-forge -c williamfgc .
