/**
 * ncioMacro.h : Define NCIO MACROS to generate and restrict possible template
 * types
 *
 * Created on: May 18, 2020
 *      Author: William F Godoy godoywf@ornl.gov
 */

#pragma once

#define NCIO_MACRO_FUNCTION_NEXUS_BANK_MAKE_ENUM(bank_id)                      \
    enum class bank_id                                                         \
    {                                                                          \
        event_id,                                                              \
        event_index,                                                           \
        event_time_offset,                                                     \
        event_time_zero,                                                       \
        total_counts                                                           \
    };

#define NCIO_MACRO_NEXUS_FOREACH_BANK_ID(MACRO)                                \
    MACRO(bank_1)                                                              \
    MACRO(bank_2)                                                              \
    MACRO(bank_3)                                                              \
    MACRO(bank_4)                                                              \
    MACRO(bank_5)                                                              \
    MACRO(bank_6)                                                              \
    MACRO(bank_7)                                                              \
    MACRO(bank_8)                                                              \
    MACRO(bank_9)                                                              \
    MACRO(bank_10)                                                             \
    MACRO(bank_11)                                                             \
    MACRO(bank_12)                                                             \
    MACRO(bank_13)                                                             \
    MACRO(bank_14)                                                             \
    MACRO(bank_15)                                                             \
    MACRO(bank_16)                                                             \
    MACRO(bank_17)                                                             \
    MACRO(bank_18)                                                             \
    MACRO(bank_19)                                                             \
    MACRO(bank_20)                                                             \
    MACRO(bank_21)                                                             \
    MACRO(bank_22)                                                             \
    MACRO(bank_23)                                                             \
    MACRO(bank_24)                                                             \
    MACRO(bank_25)                                                             \
    MACRO(bank_26)                                                             \
    MACRO(bank_27)                                                             \
    MACRO(bank_28)                                                             \
    MACRO(bank_29)                                                             \
    MACRO(bank_30)                                                             \
    MACRO(bank_31)                                                             \
    MACRO(bank_32)                                                             \
    MACRO(bank_33)                                                             \
    MACRO(bank_34)                                                             \
    MACRO(bank_35)                                                             \
    MACRO(bank_36)                                                             \
    MACRO(bank_37)                                                             \
    MACRO(bank_38)                                                             \
    MACRO(bank_39)                                                             \
    MACRO(bank_40)                                                             \
    MACRO(bank_41)                                                             \
    MACRO(bank_42)                                                             \
    MACRO(bank_43)                                                             \
    MACRO(bank_44)                                                             \
    MACRO(bank_45)                                                             \
    MACRO(bank_46)                                                             \
    MACRO(bank_47)                                                             \
    MACRO(bank_48)                                                             \
    MACRO(bank_49)                                                             \
    MACRO(bank_50)                                                             \
    MACRO(bank_51)                                                             \
    MACRO(bank_52)                                                             \
    MACRO(bank_53)                                                             \
    MACRO(bank_54)                                                             \
    MACRO(bank_55)                                                             \
    MACRO(bank_56)                                                             \
    MACRO(bank_57)                                                             \
    MACRO(bank_58)                                                             \
    MACRO(bank_59)                                                             \
    MACRO(bank_60)                                                             \
    MACRO(bank_61)                                                             \
    MACRO(bank_62)                                                             \
    MACRO(bank_63)                                                             \
    MACRO(bank_64)                                                             \
    MACRO(bank_65)                                                             \
    MACRO(bank_66)                                                             \
    MACRO(bank_67)                                                             \
    MACRO(bank_68)                                                             \
    MACRO(bank_69)                                                             \
    MACRO(bank_70)                                                             \
    MACRO(bank_71)                                                             \
    MACRO(bank_72)                                                             \
    MACRO(bank_73)                                                             \
    MACRO(bank_74)                                                             \
    MACRO(bank_75)                                                             \
    MACRO(bank_76)                                                             \
    MACRO(bank_77)                                                             \
    MACRO(bank_78)                                                             \
    MACRO(bank_79)                                                             \
    MACRO(bank_80)                                                             \
    MACRO(bank_81)                                                             \
    MACRO(bank_82)                                                             \
    MACRO(bank_83)                                                             \
    MACRO(bank_84)                                                             \
    MACRO(bank_85)                                                             \
    MACRO(bank_86)                                                             \
    MACRO(bank_87)                                                             \
    MACRO(bank_88)                                                             \
    MACRO(bank_89)                                                             \
    MACRO(bank_90)                                                             \
    MACRO(bank_91)                                                             \
    MACRO(bank_92)                                                             \
    MACRO(bank_93)                                                             \
    MACRO(bank_94)                                                             \
    MACRO(bank_95)                                                             \
    MACRO(bank_96)                                                             \
    MACRO(bank_97)                                                             \
    MACRO(bank_98)                                                             \
    MACRO(bank_99)                                                             \
    MACRO(bank_100)                                                            \
    MACRO(bank_101)                                                            \
    MACRO(bank_102)                                                            \
    MACRO(bank_103)                                                            \
    MACRO(bank_104)                                                            \
    MACRO(bank_105)                                                            \
    MACRO(bank_106)                                                            \
    MACRO(bank_107)                                                            \
    MACRO(bank_108)                                                            \
    MACRO(bank_109)                                                            \
    MACRO(bank_110)                                                            \
    MACRO(bank_111)                                                            \
    MACRO(bank_112)                                                            \
    MACRO(bank_113)                                                            \
    MACRO(bank_114)                                                            \
    MACRO(bank_115)                                                            \
    MACRO(bank_116)                                                            \
    MACRO(bank_117)                                                            \
    MACRO(bank_118)                                                            \
    MACRO(bank_119)                                                            \
    MACRO(bank_120)                                                            \
    MACRO(bank_121)                                                            \
    MACRO(bank_122)                                                            \
    MACRO(bank_123)                                                            \
    MACRO(bank_124)                                                            \
    MACRO(bank_125)                                                            \
    MACRO(bank_126)                                                            \
    MACRO(bank_127)                                                            \
    MACRO(bank_128)                                                            \
    MACRO(bank_129)                                                            \
    MACRO(bank_130)                                                            \
    MACRO(bank_131)                                                            \
    MACRO(bank_132)                                                            \
    MACRO(bank_133)                                                            \
    MACRO(bank_134)                                                            \
    MACRO(bank_135)                                                            \
    MACRO(bank_136)                                                            \
    MACRO(bank_137)                                                            \
    MACRO(bank_138)                                                            \
    MACRO(bank_139)                                                            \
    MACRO(bank_140)                                                            \
    MACRO(bank_141)                                                            \
    MACRO(bank_142)                                                            \
    MACRO(bank_143)                                                            \
    MACRO(bank_144)                                                            \
    MACRO(bank_145)                                                            \
    MACRO(bank_146)                                                            \
    MACRO(bank_147)                                                            \
    MACRO(bank_148)                                                            \
    MACRO(bank_149)                                                            \
    MACRO(bank_150)                                                            \
    MACRO(bank_151)                                                            \
    MACRO(bank_152)                                                            \
    MACRO(bank_153)                                                            \
    MACRO(bank_154)                                                            \
    MACRO(bank_155)                                                            \
    MACRO(bank_156)                                                            \
    MACRO(bank_157)                                                            \
    MACRO(bank_158)                                                            \
    MACRO(bank_159)                                                            \
    MACRO(bank_160)                                                            \
    MACRO(bank_161)                                                            \
    MACRO(bank_162)                                                            \
    MACRO(bank_163)                                                            \
    MACRO(bank_164)                                                            \
    MACRO(bank_165)                                                            \
    MACRO(bank_166)                                                            \
    MACRO(bank_167)                                                            \
    MACRO(bank_168)                                                            \
    MACRO(bank_169)                                                            \
    MACRO(bank_170)                                                            \
    MACRO(bank_171)                                                            \
    MACRO(bank_172)                                                            \
    MACRO(bank_173)                                                            \
    MACRO(bank_174)                                                            \
    MACRO(bank_175)                                                            \
    MACRO(bank_176)                                                            \
    MACRO(bank_177)                                                            \
    MACRO(bank_178)                                                            \
    MACRO(bank_179)                                                            \
    MACRO(bank_180)                                                            \
    MACRO(bank_181)                                                            \
    MACRO(bank_182)                                                            \
    MACRO(bank_183)                                                            \
    MACRO(bank_184)                                                            \
    MACRO(bank_185)                                                            \
    MACRO(bank_186)                                                            \
    MACRO(bank_187)                                                            \
    MACRO(bank_188)                                                            \
    MACRO(bank_189)                                                            \
    MACRO(bank_190)                                                            \
    MACRO(bank_191)                                                            \
    MACRO(bank_192)                                                            \
    MACRO(bank_193)                                                            \
    MACRO(bank_194)                                                            \
    MACRO(bank_195)                                                            \
    MACRO(bank_196)                                                            \
    MACRO(bank_197)                                                            \
    MACRO(bank_198)                                                            \
    MACRO(bank_199)                                                            \
    MACRO(bank_200)                                                            \
    MACRO(bank_201)                                                            \
    MACRO(bank_202)                                                            \
    MACRO(bank_203)                                                            \
    MACRO(bank_204)                                                            \
    MACRO(bank_205)                                                            \
    MACRO(bank_206)                                                            \
    MACRO(bank_207)                                                            \
    MACRO(bank_208)                                                            \
    MACRO(bank_209)                                                            \
    MACRO(bank_210)                                                            \
    MACRO(bank_211)                                                            \
    MACRO(bank_212)                                                            \
    MACRO(bank_213)                                                            \
    MACRO(bank_214)                                                            \
    MACRO(bank_215)                                                            \
    MACRO(bank_216)                                                            \
    MACRO(bank_217)                                                            \
    MACRO(bank_218)                                                            \
    MACRO(bank_219)                                                            \
    MACRO(bank_220)                                                            \
    MACRO(bank_221)                                                            \
    MACRO(bank_222)                                                            \
    MACRO(bank_223)                                                            \
    MACRO(bank_224)                                                            \
    MACRO(bank_225)                                                            \
    MACRO(bank_226)                                                            \
    MACRO(bank_227)                                                            \
    MACRO(bank_228)                                                            \
    MACRO(bank_229)                                                            \
    MACRO(bank_230)                                                            \
    MACRO(bank_231)                                                            \
    MACRO(bank_232)                                                            \
    MACRO(bank_233)                                                            \
    MACRO(bank_234)                                                            \
    MACRO(bank_235)                                                            \
    MACRO(bank_236)                                                            \
    MACRO(bank_237)                                                            \
    MACRO(bank_238)                                                            \
    MACRO(bank_239)                                                            \
    MACRO(bank_240)                                                            \
    MACRO(bank_241)                                                            \
    MACRO(bank_242)                                                            \
    MACRO(bank_243)                                                            \
    MACRO(bank_244)                                                            \
    MACRO(bank_245)                                                            \
    MACRO(bank_246)                                                            \
    MACRO(bank_247)                                                            \
    MACRO(bank_248)                                                            \
    MACRO(bank_249)                                                            \
    MACRO(bank_250)                                                            \
    MACRO(bank_251)                                                            \
    MACRO(bank_252)                                                            \
    MACRO(bank_253)                                                            \
    MACRO(bank_254)                                                            \
    MACRO(bank_255)                                                            \
    MACRO(bank_256)                                                            \
    MACRO(bank_error)                                                          \
    MACRO(bank_unmapped)
