
name: GitHub Actions

on: 
  push: 
    branches: 
    - master 
  pull_request: 
    branches: 
    - master 

jobs:
  linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_YML_JOBNAME: ${{ matrix.jobname }}
      GH_YML_OS: Linux
      
    strategy:
      fail-fast: false
      matrix:
        jobname: [
          ubuntu
        ]
    
    steps:
    - name: Update System Repos
      run: /bin/sh -c "sudo apt-get update"

    - name: Setup Dependencies
      run: /bin/sh -c "sudo apt-get install ninja-build meson -y"

    - name: Checkout Action
      uses: actions/checkout@v1

    - name: Configure
      run: /bin/sh -c "cd ${GITHUB_WORKSPACE}/.. && mkdir ncio-build && cd ncio-build && meson --prefix=${GITHUB_WORKSPACE}/../ncio-install .."

    - name: Build
      run: /bin/sh -c "cd ${GITHUB_WORKSPACE}/../ncio-build && ninja"

    - name: Test
      run: /bin/sh -c "cd ${GITHUB_WORKSPACE}/../ncio-build && ninja test"

    - name: Install
      run: /bin/sh -c "cd ${GITHUB_WORKSPACE}/../ncio-build && ninja install"
