
name: GitHub Actions

on: 
  push: 
    branches: 
    - master 
  pull_request: 
    branches: 
    - master 

jobs:
  linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [
          ubuntu18-gcc8,
          centos7-gcc8
        ]
        include:
        - jobname: ubuntu18-gcc8
          container: 
            image: williamfgc/ncio-ci:ubuntu18-gcc8-clang6
            options: -u root
        - jobname: centos7-gcc8
          container: 
            image: williamfgc/ncio-ci:centos7-gcc8-clang5
            options: -u root

    steps:
    - name: Checkout Action
      uses: actions/checkout@v1
      
    - name: Setup Dependencies
      run: scripts/ci/github-actions/bash/setup_linux.sh

    - name: Configure
      run: scripts/ci/github-actions/bash/run_step.sh configure

    - name: Build
      run: scripts/ci/github-actions/bash/run_step.sh build

    - name: Test
      run: scripts/ci/github-actions/bash/run_step.sh test

    - name: Install
      run: scripts/ci/github-actions/bash/run_step.sh install


  macos:
    runs-on: macos-latest
    env:
      GH_YML_JOBNAME: ${{ matrix.jobname }}
      GH_YML_OS: macOS

    strategy:
      fail-fast: false
      matrix:
        jobname: [
          macos1015-xcode11 
        ]

    steps:
    - name: Checkout Action
      uses: actions/checkout@v1

    - name: Setup Dependencies
      run: scripts/ci/github-actions/bash/setup_macos.sh

    - name: Configure
      run: scripts/ci/github-actions/bash/run_step.sh configure

    - name: Build
      run: scripts/ci/github-actions/bash/run_step.sh build

    - name: Test
      run: scripts/ci/github-actions/bash/run_step.sh test

    - name: Install
      run: scripts/ci/github-actions/bash/run_step.sh install
  
  windows:
    runs-on: windows-2016
    env:
      GH_YML_JOBNAME: ${{ matrix.jobname }}
      GH_YML_OS: windows

    strategy:
      fail-fast: false
      matrix:
        jobname: [
          windows-vs2017
        ]

    steps:
    - name: Checkout Action
      uses: actions/checkout@v1
    
    - name: Setup Dependencies
      run: scripts/ci/github-actions/powershell/setup_windows.ps1
      
    - name: Set MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure
      run: scripts/ci/github-actions/powershell/run_step.ps1 -step configure

    - name: Build
      run: scripts/ci/github-actions/powershell/run_step.ps1 -step build

    - name: Test
      run: scripts/ci/github-actions/powershell/run_step.ps1 -step test

    - name: Install
      run: scripts/ci/github-actions/powershell/run_step.ps1 -step install
