
name: GitHub Actions manual CI

on: 
  pull_request:
    types: [opened]
  
  issue_comment:
    types: [created]
  
  push:
    branches: 
    - main
  
jobs:

  linux_pr_comment:
    # only run on pull request comments and merge
    if: | 
        github.repository_owner == 'ORNL' &&
        ( github.event.issue.pull_request || github.event.action == 'push' ) &&
        github.actor == 'williamfgc' &&
        contains(github.event.comment.body, 'Test this please')

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [
          ubuntu18-gcc8
        ]
        include:
        - jobname: ubuntu18-gcc8
          container: 
            image: williamfgc/ncio-ci:ubuntu18-gcc8-clang6
            options: -u root
       
    steps:
    - name: PR info
      run:  |
            echo -e "Comment on PR #${{ github.event.issue.number }}\n" \
            echo -e "Comment: ${{ github.event.comment.body }}\n" \
            echo -e "GitHub actor: ${{ github.actor }}\n"
             
    - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.2
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Action
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{fromJson(steps.request.outputs.data).head.repo.full_name}}
        ref: ${{fromJson(steps.request.outputs.data).head.ref}}

    - name: Configure
      run: scripts/ci/github-actions/bash/run_step.sh configure

    - name: Build
      run: scripts/ci/github-actions/bash/run_step.sh build

    - name: Test
      run: scripts/ci/github-actions/bash/run_step.sh test

    - name: Install
      run: scripts/ci/github-actions/bash/run_step.sh install
