
name: GitHub Actions manual CI

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  
jobs:

  linux_pr_comment:
    if: github.repository_owner == 'ORNL'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [
          ubuntu18-gcc8
        ]
        include:
        - jobname: ubuntu18-gcc8
          container: 
            image: williamfgc/ncio-ci:ubuntu18-gcc8-clang6
            options: -u root
       
    steps:
    - uses: khan/pull-request-comment-trigger@master
      id: check
      if: github.actor == 'williamfgc'
      with:
        trigger: 'Test this please'
    
    - name: Github API Request
      if: steps.check.outputs.triggered == 'true'
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Get PR informations
      if: steps.check.outputs.triggered == 'true'
      id: pr_data
      run: |
          echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
          echo "::set-output name=repo_name::${{ fromJson(steps.request.outputs.data).head.repo.full_name }}"
          echo "::set-output name=repo_clone_url::${{ fromJson(steps.request.outputs.data).head.repo.clone_url }}"
          echo "::set-output name=repo_ssh_url::${{ fromJson(steps.request.outputs.data).head.repo.ssh_url }}"
          
    - name: Checkout PR Branch
      if: steps.check.outputs.triggered == 'true'
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
        ref: ${{ steps.pr_data.outputs.branch }}
        
    - name: Configure
      if: steps.check.outputs.triggered == 'true'
      run: scripts/ci/github-actions/bash/run_step.sh configure

    - name: Build
      if: steps.check.outputs.triggered == 'true'
      run: scripts/ci/github-actions/bash/run_step.sh build

    - name: Test
      if: steps.check.outputs.triggered == 'true'
      run: scripts/ci/github-actions/bash/run_step.sh test

    - name: Install
      if: steps.check.outputs.triggered == 'true'
      run: scripts/ci/github-actions/bash/run_step.sh install
    
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Manual
        conclusion: ${{ job.status }}
    
    - name: Create status check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          BUILD_COMMIT=$(git rev-parse HEAD)
          curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/{org}/{repo}/check-runs \
          -d '{"name":"build", "head_sha": "'"$BUILD_COMMIT"'", "status": "completed", "conclusion": "success" }'

