
name: GitHub Actions manual CI

on: 
  issue_comment:
    types: [created]
  
  push:
    branches: 
    - main
  
jobs:

  linux:
    # only run on pull request comments
    if: | 
        github.repository_owner == 'ORNL' &&
        ${{ github.event.issue.pull_request }} &&
        contains(github.event.issue.comment, 'Test this please') &&
        github.actor == 'williamfgc'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [
          ubuntu18-gcc8
        ]
        include:
        - jobname: ubuntu18-gcc8
          container: 
            image: williamfgc/ncio-ci:ubuntu18-gcc8-clang6
            options: -u root
       
    steps:
    - name: PR info
    - run: |
            echo "Comment on PR #${{ github.event.issue.number }}"
            echo "Comment: ${{ github.event.issue.comment }}"
            echo "Comment sender: ${{ github.event.issue.comment.sender }}"
            echo "GitHub action: ${{ github.actor }}"
             
    - name: Checkout Action
      uses: actions/checkout@v2

    - name: Configure
      run: scripts/ci/github-actions/bash/run_step.sh configure

    - name: Build
      run: scripts/ci/github-actions/bash/run_step.sh build

    - name: Test
      run: scripts/ci/github-actions/bash/run_step.sh test

    - name: Install
      run: scripts/ci/github-actions/bash/run_step.sh install
