
name: GitHub Actions Nightly

on: 
  schedule:
    - cron: '0 21 * * *' # run at 9 PM UTC (4 PM EST) 

jobs:

  linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [
          centos7-gcc8,
          centos7-clang6.0
        ]
        include:
        - jobname: centos7-gcc8
          container: 
            image: williamfgc/ncio-ci:centos7-gcc8-clang6.0
            options: -u root
        - jobname: centos7-clang6.0
          container: 
            image: williamfgc/ncio-ci:centos7-gcc8-clang6.0
            options: -u root

    steps:
    - name: Checkout Action
      uses: actions/checkout@v1

    - name: Configure
      run: scripts/nightly/github-actions/bash/run_step.sh configure

    - name: Build
      run: scripts/nightly/github-actions/bash/run_step.sh build

    - name: Test
      run: scripts/nightly/github-actions/bash/run_step.sh test
